#!/usr/bin/env bash
# Author: Mislav Marohnić
# https://github.com/mislav/dotfiles
#
# rebase-authors` adds authorship info to interactive git rebase output

set -e

while read action sha other; do
  if [ -n "$action" ]; then
    echo -n "$action "
    git show $sha --format="%h [%an] %s" -s
  else
    echo
  fi
done
